#!/bin/sh
if [[ -d "/Applications/Visual Studio Code.app" ]]; then
    export PATH=$PATH:/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin
fi
if [[ -d "/Applications/VSCodium.app" ]]; then
   export PATH=$PATH:/Applications/VSCodium.app/Contents/Resources/app/bin
fi
