# brew bundle install -v --file $HOME/Brewfile

tap "homebrew/cask"

brew "stow"
brew "bash"
brew "bash-completion@2"
brew "git"
brew "emacs"
brew "the_silver_searcher"
brew "findutils" # GNU find, xargs, locate
brew "jq"

#cask "1password"
cask "1password-cli"
cask "slack"
cask "bartender"
cask "witch"
cask "signal"
cask "alfred"
cask "spotify"

brew "mas"

mas "The Clock", id: 488764545
mas "Todoist", id: 585829637

tap "homebrew/cask-fonts"
cask "font-hack"

mas "Airmail", id: 918858936
#mas "Divvy", id: 413857545 # Not M1 compatible
mas "MiniPlay", id: 936243210

cask "sublime-text"
cask "dash"

brew "awscli"
cask "aws-vault"

brew "grep"
brew "watch"
brew "coreutils"

cask "macdown"
#cask "karabiner-elements"
